// ------ ENUMS ------
export enum ActionTypes {
  SET_ITEMS = 'SET_ITEMS',
  SET_ITEMS_IN_CART = 'SET_ITEMS_IN_CART',
  INCREMENT_ITEMS = 'INCREMENT_ITEMS',
  DECREMENT_ITEMS = 'DECREMENT_ITEMS',
  CHANGE_QTY = 'CHANGE_QTY',
  SEND_ITEMS_TO_CART = 'SEND_ITEMS_TO_CART',
  REMOVE_ITEMS_IN_CART = 'REMOVE_ITEMS_IN_CART',
  CLEAR_CART = 'CLEAR_CART',
}
